#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_charpicker_data.py
Генератор JSON-файла данных для charPicker v3.0

Источник: Unicode Emoji 15.1 (2023) + Unicode 15.0 спецсимволы
Запуск:
    python3 generate_charpicker_data.py
    python3 generate_charpicker_data.py --output my-data.json
    python3 generate_charpicker_data.py --minify
"""

import json
import sys
import argparse

# ─── ФОРМАТ ДАННЫХ ─────────────────────────────────────────────────────────
# Каждый элемент chars:  { "c": "😀", "n": "улыбка grinning face" }
# Имена: СНАЧАЛА русское, ПОТОМ английское — для лучшего поиска по-русски.
# Группа: { "id": str, "label": str, "labelEn": str, "icon": str,
#            "subgroups": [ { "label": str, "labelEn": str, "chars": [...] } ] }
# ───────────────────────────────────────────────────────────────────────────

def c(char_str, name_ru, name_en):
    """Shorthand: создать объект символа."""
    return {"c": char_str, "n": f"{name_ru} {name_en}"}


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  ГРУППЫ ДАННЫХ                                                          ║
# ╚══════════════════════════════════════════════════════════════════════════╝

GROUPS = []

# ────────────────────────────────────────────────────────────────────────────
# 1. СМАЙЛЫ И ЛЮДИ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "smileys",
    "label": "Смайлы и люди",
    "labelEn": "Smileys & People",
    "icon": "😀",
    "subgroups": [
        {
            "label": "Счастье",
            "labelEn": "Happy faces",
            "chars": [
                c("😀","широкая улыбка","grinning face"),
                c("😃","улыбка с большими глазами","grinning face big eyes"),
                c("😄","улыбка с закрытыми глазами","grinning face smiling eyes"),
                c("😁","сияющая улыбка","beaming face smiling eyes"),
                c("😆","улыбка щурясь","grinning squinting face"),
                c("😅","улыбка с потом","grinning face sweat"),
                c("🤣","катаюсь со смеху","rolling on floor laughing"),
                c("😂","слёзы от смеха","face tears of joy"),
                c("🙂","слабая улыбка","slightly smiling face"),
                c("🙃","перевёрнутое лицо","upside down face"),
                c("🫠","тающее лицо","melting face"),
                c("😉","подмигивание","winking face"),
                c("😊","смущённая улыбка","smiling face blush"),
                c("😇","лицо ангела с нимбом","smiling face halo"),
                c("🥰","лицо с сердечками","smiling face hearts"),
                c("😍","глаза-сердечки","smiling face heart eyes"),
                c("🤩","звёзды в глазах","star struck"),
                c("😘","воздушный поцелуй","face blowing kiss"),
                c("😗","поцелуй","kissing face"),
                c("😚","поцелуй с закрытыми глазами","kissing face closed eyes"),
                c("😙","поцелуй с улыбкой","kissing smiling eyes"),
                c("🥲","улыбаюсь сквозь слёзы","smiling face tear"),
                c("😋","вкусно, облизываюсь","face savoring food"),
                c("😛","язык","face tongue"),
                c("😜","подмигиваю с языком","winking face tongue"),
                c("🤪","безумная улыбка","zany face"),
                c("😝","язык и закрытые глаза","squinting face tongue"),
            ]
        },
        {
            "label": "Нейтральные и задумчивые",
            "labelEn": "Neutral & pensive",
            "chars": [
                c("🤑","деньги в глазах","money mouth face"),
                c("🤗","обнимашки","hugging face"),
                c("🤭","рот рукой","face hand over mouth"),
                c("🫢","широко открытые глаза","face open eyes hand over mouth"),
                c("🫣","подглядываю","face peeking eye"),
                c("🤫","тсс","shushing face"),
                c("🤔","задумался","thinking face"),
                c("🫡","честь","saluting face"),
                c("🤐","молчу рот на замке","zipper mouth face"),
                c("🤨","одна бровь поднята","face raised eyebrow"),
                c("😐","нейтральное лицо","neutral face"),
                c("😑","без выражения","expressionless face"),
                c("😶","лицо без рта","face without mouth"),
                c("🫥","пунктирное лицо","dotted line face"),
                c("😶‍🌫️","лицо в тумане","face in clouds"),
                c("😏","ухмылка","smirking face"),
                c("😒","недовольное лицо","unamused face"),
                c("🙄","закатываю глаза","face rolling eyes"),
                c("😬","гримаса","grimacing face"),
                c("🤥","лгу","lying face"),
                c("🫨","трясущееся лицо","shaking face"),
            ]
        },
        {
            "label": "Грусть и тревога",
            "labelEn": "Sad & worried",
            "chars": [
                c("😔","задумчивое лицо","pensive face"),
                c("😪","сонное лицо","sleepy face"),
                c("🤤","слюнки текут","drooling face"),
                c("😴","сплю","sleeping face"),
                c("😷","маска на лице","face medical mask"),
                c("🤒","больной с термометром","face thermometer"),
                c("🤕","голова в повязке","face head bandage"),
                c("🤢","тошнота","nauseated face"),
                c("🤮","рвота","face vomiting"),
                c("🤧","чихаю","sneezing face"),
                c("🥵","жарко","hot face"),
                c("🥶","холодно","cold face"),
                c("🥴","качает","woozy face"),
                c("😵","головокружение","dizzy face"),
                c("😵‍💫","звёздочки в глазах","face spiral eyes"),
                c("🤯","взрыв мозга","exploding head"),
                c("😕","растерянное лицо","confused face"),
                c("🫤","рот набок","face diagonal mouth"),
                c("😟","обеспокоенное лицо","worried face"),
                c("🙁","слегка грустное лицо","slightly frowning face"),
                c("☹️","грустное лицо","frowning face"),
                c("😮","рот открыт","face open mouth"),
                c("😯","изумлённое лицо","hushed face"),
                c("😲","поражённое лицо","astonished face"),
                c("😳","покраснело лицо","flushed face"),
                c("🥺","умоляющие глаза","pleading face"),
                c("🥹","сдерживаю слёзы","face holding back tears"),
                c("😦","хмурое лицо с открытым ртом","frowning face open mouth"),
                c("😧","страдальческое лицо","anguished face"),
                c("😨","испуганное лицо","fearful face"),
                c("😰","тревожное лицо","anxious face sweat"),
                c("😥","грустное лицо с потом","sad relieved face"),
                c("😢","плачу","crying face"),
                c("😭","горько плачу","loudly crying face"),
                c("😱","кричу от страха","face screaming fear"),
                c("😖","растерянное недовольство","confounded face"),
                c("😣","измученное лицо","persevering face"),
                c("😞","разочарованное лицо","disappointed face"),
                c("😓","в холодном поту","downcast face sweat"),
                c("😩","утомлённое лицо","weary face"),
                c("😫","уставшее лицо","tired face"),
                c("🥱","зеваю","yawning face"),
            ]
        },
        {
            "label": "Озорные и особые",
            "labelEn": "Playful & special",
            "chars": [
                c("😤","пыхтю","face steam nose"),
                c("😠","злое лицо","angry face"),
                c("😡","разъярённое лицо","pouting face"),
                c("🤬","ругаюсь","face symbols mouth"),
                c("😈","злорадная улыбка дьяволёнка","smiling face horns"),
                c("👿","злой дьяволёнок","angry face horns"),
                c("💀","череп","skull"),
                c("☠️","череп и кости","skull crossbones"),
                c("💩","кучка","pile of poo"),
                c("🤡","клоун","clown face"),
                c("👹","демон огр","ogre"),
                c("👺","гоблин","goblin"),
                c("👻","привидение","ghost"),
                c("👽","инопланетянин","alien"),
                c("👾","пришелец","alien monster"),
                c("🤖","робот","robot"),
                c("😺","улыбающийся кот","grinning cat"),
                c("😸","кот с улыбкой","grinning cat smiling eyes"),
                c("😹","кот со слезами смеха","cat tears of joy"),
                c("😻","кот с сердечками","smiling cat heart eyes"),
                c("😼","кот ухмыляется","cat wry smile"),
                c("😽","кот целует","kissing cat"),
                c("🙀","поражённый кот","weary cat"),
                c("😿","плачущий кот","crying cat"),
                c("😾","сердитый кот","pouting cat"),
            ]
        },
        {
            "label": "Люди и внешность",
            "labelEn": "People & appearance",
            "chars": [
                c("👶","младенец","baby"),
                c("🧒","ребёнок","child"),
                c("👦","мальчик","boy"),
                c("👧","девочка","girl"),
                c("🧑","человек","person"),
                c("👱","блондин","person blond hair"),
                c("👨","мужчина","man"),
                c("🧔","бородач","person beard"),
                c("👩","женщина","woman"),
                c("🧓","пожилой человек","older person"),
                c("👴","старик","old man"),
                c("👵","старушка","old woman"),
                c("🙍","хмурится","person frowning"),
                c("🙎","дуется","person pouting"),
                c("🙅","жест нет","person gesturing no"),
                c("🙆","жест ок","person gesturing ok"),
                c("💁","информация","person tipping hand"),
                c("🙋","поднимает руку","person raising hand"),
                c("🧏","язык жестов","deaf person"),
                c("🙇","кланяется","person bowing"),
                c("🤦","лицо в ладонях","person facepalming"),
                c("🤷","пожимает плечами","person shrugging"),
            ]
        },
        {
            "label": "Профессии",
            "labelEn": "Professions",
            "chars": [
                c("👮","полицейский","police officer"),
                c("🕵️","детектив","detective"),
                c("💂","охранник","guard"),
                c("🥷","ниндзя","ninja"),
                c("👷","строитель","construction worker"),
                c("🫅","корона","person crown"),
                c("🤴","принц","prince"),
                c("👸","принцесса","princess"),
                c("👳","тюрбан","person wearing turban"),
                c("👲","кепка","person skullcap"),
                c("🧕","хиджаб","woman headscarf"),
                c("🤵","смокинг","person tuxedo"),
                c("👰","фата","person veil"),
                c("🫄","беременный","pregnant person"),
                c("🤱","кормление грудью","breast feeding"),
                c("👼","купидон","baby angel"),
                c("🎅","дед мороз","santa claus"),
                c("🤶","снегурочка","mrs claus"),
                c("🧑‍🎄","клаус","mx claus"),
                c("🦸","супергерой","superhero"),
                c("🦹","суперзлодей","supervillain"),
                c("🧙","маг","mage"),
                c("🧚","фея","fairy"),
                c("🧛","вампир","vampire"),
                c("🧜","русалка","merperson"),
                c("🧝","эльф","elf"),
                c("🧞","джинн","genie"),
                c("🧟","зомби","zombie"),
                c("🧌","тролль","troll"),
                c("💆","массаж лица","person getting massage"),
                c("💇","стрижка","person getting haircut"),
                c("🚶","идёт","person walking"),
                c("🧍","стоит","person standing"),
                c("🧎","на коленях","person kneeling"),
                c("🏃","бежит","person running"),
                c("💃","танцует женщина","woman dancing"),
                c("🕺","танцует мужчина","man dancing"),
                c("🕴️","человек в костюме","person suit levitating"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 2. ЖЕСТЫ И ТЕЛО
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "gestures",
    "label": "Жесты и тело",
    "labelEn": "Gestures & Body",
    "icon": "👋",
    "subgroups": [
        {
            "label": "Руки — жесты",
            "labelEn": "Hand gestures",
            "chars": [
                c("👋","привет помахать рукой","waving hand"),
                c("🤚","поднятая рука тыльной стороной","raised back hand"),
                c("🖐️","поднятая рука пятью пальцами","hand fingers splayed"),
                c("✋","поднятая рука","raised hand"),
                c("🖖","рукопожатие Вулкан","vulcan salute"),
                c("🫱","рука вправо","rightwards hand"),
                c("🫲","рука влево","leftwards hand"),
                c("🫳","рука вниз ладонью","palm down hand"),
                c("🫴","рука ладонью вверх","palm up hand"),
                c("🫷","левый кулак","leftward pushing hand"),
                c("🫸","правый кулак","rightward pushing hand"),
                c("👌","окей ОК","ok hand"),
                c("🤌","итальянский жест","pinched fingers"),
                c("🤏","немного чуть-чуть","pinching hand"),
                c("✌️","два пальца победа","victory hand"),
                c("🤞","скрещенные пальцы удача","crossed fingers"),
                c("🫰","щелчок пальцами","hand index finger thumb crossed"),
                c("🤟","любовь рок","love you gesture"),
                c("🤘","коза рок рога","sign of horns"),
                c("🤙","позвони мне","call me hand"),
                c("👈","указывает влево","backhand index left"),
                c("👉","указывает вправо","backhand index right"),
                c("👆","указывает вверх","backhand index up"),
                c("🖕","средний палец","middle finger"),
                c("👇","указывает вниз","backhand index down"),
                c("☝️","один палец вверх","index pointing up"),
                c("🫵","указывает на тебя","index pointing at viewer"),
                c("👍","лайк большой палец вверх","thumbs up"),
                c("👎","дизлайк большой палец вниз","thumbs down"),
                c("✊","кулак","raised fist"),
                c("👊","кулак удар","oncoming fist"),
                c("🤛","левый кулак","left facing fist"),
                c("🤜","правый кулак","right facing fist"),
                c("👏","аплодисменты хлопки","clapping hands"),
                c("🙌","поднятые руки","raising hands"),
                c("🫶","сердце из рук","heart hands"),
                c("👐","открытые руки","open hands"),
                c("🤲","ладони чаша","palms up together"),
                c("🤝","рукопожатие","handshake"),
                c("🙏","молюсь пожалуйста спасибо","folded hands"),
            ]
        },
        {
            "label": "Части тела",
            "labelEn": "Body parts",
            "chars": [
                c("✍️","пишу от руки","writing hand"),
                c("💅","лак для ногтей маникюр","nail polish"),
                c("🤳","селфи","selfie"),
                c("💪","мышца сила","flexed biceps"),
                c("🦾","механическая рука","mechanical arm"),
                c("🦿","механическая нога","mechanical leg"),
                c("🦵","нога","leg"),
                c("🦶","ступня","foot"),
                c("👂","ухо","ear"),
                c("🦻","ухо с аппаратом","ear hearing aid"),
                c("👃","нос","nose"),
                c("🫀","сердце анатомическое","anatomical heart"),
                c("🫁","лёгкие","lungs"),
                c("🧠","мозг","brain"),
                c("🦷","зуб","tooth"),
                c("🦴","кость","bone"),
                c("👀","глаза","eyes"),
                c("👁️","глаз","eye"),
                c("👅","язык","tongue"),
                c("👄","губы","mouth"),
                c("🫦","прикусываю губу","biting lip"),
            ]
        },
        {
            "label": "Семья и пары",
            "labelEn": "Family & couples",
            "chars": [
                c("👫","мужчина и женщина вместе","woman and man holding hands"),
                c("👬","двое мужчин","men holding hands"),
                c("👭","двое женщин","women holding hands"),
                c("💏","поцелуй","kiss"),
                c("💑","пара в любви","couple heart"),
                c("👪","семья","family"),
                c("🗣️","говорю","speaking head"),
                c("👤","силуэт","bust silhouette"),
                c("👥","силуэты","busts silhouettes"),
                c("🫂","объятия","people hugging"),
                c("👣","следы ног","footprints"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 3. ЖИВОТНЫЕ И ПРИРОДА
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "nature",
    "label": "Природа",
    "labelEn": "Nature",
    "icon": "🌿",
    "subgroups": [
        {
            "label": "Млекопитающие",
            "labelEn": "Mammals",
            "chars": [
                c("🐶","собака","dog face"),
                c("🐱","кот","cat face"),
                c("🐭","мышь","mouse face"),
                c("🐹","хомяк","hamster face"),
                c("🐰","кролик","rabbit face"),
                c("🦊","лиса","fox face"),
                c("🐻","медведь","bear face"),
                c("🐼","панда","panda face"),
                c("🐻‍❄️","белый медведь","polar bear"),
                c("🐨","коала","koala"),
                c("🐯","тигр","tiger face"),
                c("🦁","лев","lion face"),
                c("🐮","корова","cow face"),
                c("🐷","свинья","pig face"),
                c("🐸","лягушка","frog face"),
                c("🐵","обезьяна","monkey face"),
                c("🙈","не вижу","see no evil monkey"),
                c("🙉","не слышу","hear no evil monkey"),
                c("🙊","не говорю","speak no evil monkey"),
                c("🐔","курица","chicken"),
                c("🐧","пингвин","penguin"),
                c("🐦","птица","bird"),
                c("🦅","орёл","eagle"),
                c("🦆","утка","duck"),
                c("🦉","сова","owl"),
                c("🦇","летучая мышь","bat"),
                c("🐺","волк","wolf face"),
                c("🐗","дикий кабан","boar"),
                c("🐴","лошадь","horse face"),
                c("🦄","единорог","unicorn face"),
                c("🐝","пчела","honeybee"),
                c("🪱","червяк","worm"),
                c("🐛","гусеница","bug"),
                c("🦋","бабочка","butterfly"),
                c("🐌","улитка","snail"),
                c("🐞","божья коровка","lady beetle"),
                c("🐜","муравей","ant"),
                c("🦟","комар","mosquito"),
                c("🦗","сверчок","cricket"),
                c("🕷️","паук","spider"),
                c("🦂","скорпион","scorpion"),
                c("🐢","черепаха","turtle"),
                c("🐍","змея","snake"),
                c("🦎","ящерица","lizard"),
                c("🦖","тираннозавр","t-rex"),
                c("🦕","зауропод","sauropod"),
                c("🐙","осьминог","octopus"),
                c("🦑","кальмар","squid"),
                c("🦐","креветка","shrimp"),
                c("🦞","омар","lobster"),
                c("🦀","краб","crab"),
                c("🐡","рыба фугу","blowfish"),
                c("🐠","тропическая рыба","tropical fish"),
                c("🐟","рыба","fish"),
                c("🐬","дельфин","dolphin"),
                c("🐳","кит","spouting whale"),
                c("🦈","акула","shark"),
                c("🐊","крокодил","crocodile"),
                c("🦓","зебра","zebra"),
                c("🦍","горилла","gorilla"),
                c("🦧","орангутан","orangutan"),
                c("🦣","мамонт","mammoth"),
                c("🐘","слон","elephant"),
                c("🦛","носорог","rhinoceros"),
                c("🦏","бегемот","hippopotamus"),
                c("🐪","верблюд","camel"),
                c("🐫","двугорбый верблюд","two hump camel"),
                c("🦒","жираф","giraffe"),
                c("🦘","кенгуру","kangaroo"),
                c("🦬","бизон","bison"),
                c("🐃","буйвол","water buffalo"),
                c("🐂","бык","ox"),
                c("🐄","корова","cow"),
                c("🐎","лошадь","horse"),
                c("🐖","свинья","pig"),
                c("🐏","баран","ram"),
                c("🐑","овца","ewe"),
                c("🦙","лама","llama"),
                c("🐐","коза","goat"),
                c("🦌","олень","deer"),
                c("🦫","бобёр","beaver"),
                c("🐕","собака","dog"),
                c("🐩","пудель","poodle"),
                c("🦮","собака-поводырь","guide dog"),
                c("🐈","кот","cat"),
                c("🐈‍⬛","чёрный кот","black cat"),
                c("🪶","перо","feather"),
                c("🐓","петух","rooster"),
                c("🦃","индейка","turkey"),
                c("🦤","додо","dodo"),
                c("🦚","павлин","peacock"),
                c("🦜","попугай","parrot"),
                c("🦢","лебедь","swan"),
                c("🦩","фламинго","flamingo"),
                c("🕊️","голубь","dove"),
                c("🐇","кролик","rabbit"),
                c("🦝","енот","raccoon"),
                c("🦨","скунс","skunk"),
                c("🦡","барсук","badger"),
                c("🦦","выдра","otter"),
                c("🦥","ленивец","sloth"),
                c("🐁","мышь","mouse"),
                c("🐀","крыса","rat"),
                c("🐿️","бурундук","chipmunk"),
                c("🦔","ёж","hedgehog"),
            ]
        },
        {
            "label": "Растения",
            "labelEn": "Plants",
            "chars": [
                c("🌸","цветущая вишня сакура","cherry blossom"),
                c("💮","белый цветок","white flower"),
                c("🪷","лотос","lotus"),
                c("🏵️","розетка","rosette"),
                c("🌹","роза","rose"),
                c("🥀","завядшая роза","wilted flower"),
                c("🌺","гибискус","hibiscus"),
                c("🌻","подсолнух","sunflower"),
                c("🌼","цветок","blossom"),
                c("🌷","тюльпан","tulip"),
                c("🪻","гиацинт","hyacinth"),
                c("🌱","росток","seedling"),
                c("🪴","комнатное растение","potted plant"),
                c("🌲","хвойное дерево","evergreen tree"),
                c("🌳","дерево","deciduous tree"),
                c("🌴","пальма","palm tree"),
                c("🌵","кактус","cactus"),
                c("🌾","колос пшеница","sheaf of rice"),
                c("🍀","клевер удача","four leaf clover"),
                c("🍁","кленовый лист","maple leaf"),
                c("🍂","опавший лист","fallen leaf"),
                c("🍃","листья на ветру","leaf fluttering"),
                c("🪨","камень скала","rock"),
                c("🪵","бревно дерево","wood"),
                c("🌿","трава зелень","herb"),
                c("☘️","клевер","shamrock"),
                c("🌊","волна","water wave"),
                c("🔥","огонь пламя","fire"),
                c("✨","блёстки искры","sparkles"),
                c("⭐","звезда","star"),
                c("🌟","сияющая звезда","glowing star"),
                c("💫","головокружение звёздочка","dizzy star"),
                c("❄️","снежинка","snowflake"),
                c("🌈","радуга","rainbow"),
                c("☀️","солнце","sun"),
                c("🌤️","солнце с облачком","sun small cloud"),
                c("⛅","частично облачно","partly cloudy"),
                c("🌥️","облака","cloud sun"),
                c("☁️","облако","cloud"),
                c("🌦️","солнце и дождь","sun rain"),
                c("🌧️","дождь","cloud rain"),
                c("⛈️","гроза","thunderstorm"),
                c("🌩️","молния","lightning bolt cloud"),
                c("🌨️","снег","cloud snow"),
                c("🌬️","ветер","wind face"),
                c("💨","порыв ветра","dashing away"),
                c("💧","капля воды","droplet"),
                c("💦","брызги воды","sweat droplets"),
                c("🌙","луна","crescent moon"),
                c("🌚","новолуние","new moon face"),
                c("🌛","растущая луна","first quarter moon face"),
                c("🌝","полная луна лицо","full moon face"),
                c("🌞","солнце лицо","sun face"),
                c("⚡","молния","lightning high voltage"),
                c("🌀","циклон вихрь","cyclone"),
                c("🌈","радуга","rainbow"),
                c("🌂","зонт","closed umbrella"),
                c("⛱","зонт на пляже","umbrella beach"),
                c("⛄","снеговик","snowman"),
                c("🌍","земля европа африка","earth europe africa"),
                c("🌎","земля америка","earth americas"),
                c("🌏","земля азия","earth asia australia"),
                c("🌐","земной шар меридианы","globe meridians"),
                c("🗺️","карта мира","world map"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 4. ЕДА И НАПИТКИ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "food",
    "label": "Еда и напитки",
    "labelEn": "Food & Drink",
    "icon": "🍕",
    "subgroups": [
        {
            "label": "Фрукты и овощи",
            "labelEn": "Fruit & Vegetables",
            "chars": [
                c("🍇","виноград","grapes"),
                c("🍈","дыня","melon"),
                c("🍉","арбуз","watermelon"),
                c("🍊","мандарин апельсин","tangerine"),
                c("🍋","лимон","lemon"),
                c("🍌","банан","banana"),
                c("🍍","ананас","pineapple"),
                c("🥭","манго","mango"),
                c("🍎","красное яблоко","red apple"),
                c("🍏","зелёное яблоко","green apple"),
                c("🍐","груша","pear"),
                c("🍑","персик","peach"),
                c("🍒","вишня черешня","cherries"),
                c("🍓","клубника","strawberry"),
                c("🫐","черника","blueberries"),
                c("🥝","киви","kiwi fruit"),
                c("🍅","помидор","tomato"),
                c("🫒","олива","olive"),
                c("🥥","кокос","coconut"),
                c("🥑","авокадо","avocado"),
                c("🍆","баклажан","eggplant"),
                c("🥔","картофель","potato"),
                c("🥕","морковь","carrot"),
                c("🌽","кукуруза","corn"),
                c("🌶️","острый перец чили","hot pepper"),
                c("🫑","болгарский перец","bell pepper"),
                c("🥒","огурец","cucumber"),
                c("🥬","листовая зелень","leafy green"),
                c("🥦","брокколи","broccoli"),
                c("🧄","чеснок","garlic"),
                c("🧅","лук репчатый","onion"),
                c("🍄","гриб","mushroom"),
                c("🥜","арахис","peanuts"),
                c("🫘","фасоль","beans"),
                c("🌰","каштан","chestnut"),
            ]
        },
        {
            "label": "Готовая еда",
            "labelEn": "Prepared food",
            "chars": [
                c("🍞","хлеб","bread"),
                c("🥐","круассан","croissant"),
                c("🥖","багет","baguette bread"),
                c("🫓","лепёшка","flatbread"),
                c("🥨","крендель","pretzel"),
                c("🥯","бублик","bagel"),
                c("🧀","сыр","cheese wedge"),
                c("🥚","яйцо","egg"),
                c("🍳","яичница","cooking fried egg"),
                c("🧈","масло","butter"),
                c("🥞","блины","pancakes"),
                c("🧇","вафли","waffle"),
                c("🥓","бекон","bacon"),
                c("🥩","мясо стейк","cut of meat"),
                c("🍗","куриная ножка","poultry leg"),
                c("🍖","кость с мясом","meat on bone"),
                c("🦴","кость","bone"),
                c("🌭","хот-дог","hot dog"),
                c("🍔","гамбургер","hamburger"),
                c("🍟","картошка фри","french fries"),
                c("🍕","пицца","pizza"),
                c("🫔","буррито","tamale"),
                c("🌮","тако","taco"),
                c("🌯","лаваш шаурма","burrito wrap"),
                c("🥙","питта","stuffed flatbread"),
                c("🧆","фалафель","falafel"),
                c("🥚","яйцо","egg"),
                c("🍱","бенто","bento box"),
                c("🍘","рисовый крекер","rice cracker"),
                c("🍙","рисовый шарик","rice ball"),
                c("🍚","варёный рис","cooked rice"),
                c("🍛","карри с рисом","curry rice"),
                c("🍜","рамен лапша","steaming bowl"),
                c("🍝","спагетти паста","spaghetti"),
                c("🍠","батат сладкий картофель","roasted sweet potato"),
                c("🍢","одэн","oden"),
                c("🍣","суши","sushi"),
                c("🍤","жареные креветки","fried shrimp"),
                c("🍥","нарутомаки рыбный пирог","fish cake swirl"),
                c("🥮","лунный пирог","moon cake"),
                c("🍡","данго","dango"),
                c("🧁","кекс капкейк","cupcake"),
                c("🍰","торт","shortcake"),
                c("🎂","именинный торт","birthday cake"),
                c("🍮","пудинг","custard"),
                c("🍭","леденец конфета","lollipop"),
                c("🍬","конфета","candy"),
                c("🍫","шоколад","chocolate bar"),
                c("🍿","попкорн","popcorn"),
                c("🍩","пончик","doughnut"),
                c("🍪","печенье","cookie"),
                c("🌰","каштан","chestnut"),
                c("🥧","пирог","pie"),
                c("🍯","мёд","honey pot"),
                c("🧂","соль","salt"),
                c("🍦","мороженое","soft ice cream"),
                c("🍧","щербет","shaved ice"),
                c("🍨","мороженое","ice cream"),
                c("🥗","салат","green salad"),
                c("🍲","горшочек","pot of food"),
                c("🫕","фондю","fondue"),
                c("🥘","сковорода паэлья","shallow pan food"),
                c("🍣","суши","sushi"),
            ]
        },
        {
            "label": "Напитки",
            "labelEn": "Drinks",
            "chars": [
                c("🧃","сок в коробке","beverage box"),
                c("🥤","стакан с соломинкой","cup straw"),
                c("🧋","пузырьковый чай","bubble tea"),
                c("☕","кофе чай","hot beverage"),
                c("🍵","зелёный чай","teacup"),
                c("🫖","чайник","teapot"),
                c("🍶","саке","sake"),
                c("🍾","шампанское","bottle cork"),
                c("🍷","вино красное","wine glass"),
                c("🍸","коктейль","cocktail glass"),
                c("🍹","тропический коктейль","tropical drink"),
                c("🍺","пиво","beer mug"),
                c("🍻","чокаемся пивом","clinking beer mugs"),
                c("🥂","бокалы шампанского","clinking glasses"),
                c("🥃","виски","tumbler glass"),
                c("🫗","стакан","pouring liquid"),
                c("🥛","молоко","glass of milk"),
                c("🧊","лёд","ice"),
            ]
        },
        {
            "label": "Посуда и кухня",
            "labelEn": "Utensils",
            "chars": [
                c("🍽️","тарелка","plate knife fork"),
                c("🍴","вилка и нож","fork knife"),
                c("🥄","ложка","spoon"),
                c("🔪","нож","kitchen knife"),
                c("🫙","банка","jar"),
                c("🏺","амфора","amphora"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 5. ПУТЕШЕСТВИЯ И МЕСТО
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "travel",
    "label": "Путешествия",
    "labelEn": "Travel & Places",
    "icon": "✈️",
    "subgroups": [
        {
            "label": "Транспорт",
            "labelEn": "Transport",
            "chars": [
                c("🚗","машина автомобиль","automobile car"),
                c("🚕","такси","taxi"),
                c("🚙","внедорожник","sport utility vehicle"),
                c("🛻","пикап","pickup truck"),
                c("🚌","автобус","bus"),
                c("🚎","троллейбус","trolleybus"),
                c("🏎️","гоночная машина","racing car"),
                c("🚓","полицейская машина","police car"),
                c("🚑","скорая помощь","ambulance"),
                c("🚒","пожарная машина","fire engine"),
                c("🚐","минивэн","minibus"),
                c("🛵","скутер мопед","motor scooter"),
                c("🦽","инвалидная коляска ручная","manual wheelchair"),
                c("🦼","инвалидная коляска","motorized wheelchair"),
                c("🛺","рикша","auto rickshaw"),
                c("🚲","велосипед","bicycle"),
                c("🛴","самокат","kick scooter"),
                c("🛹","скейтборд","skateboard"),
                c("🛼","роликовые коньки","roller skate"),
                c("🚏","автобусная остановка","bus stop"),
                c("🚃","трамвай вагон","railway car"),
                c("🚋","трамвай","tram car"),
                c("🚞","горная дорога","mountain railway"),
                c("🚝","монорельс","monorail"),
                c("🚄","скоростной поезд","high speed train"),
                c("🚅","пуля поезд","bullet train"),
                c("🚆","поезд","train"),
                c("🚇","метро","metro"),
                c("🚈","лёгкое метро","light rail"),
                c("🚉","станция","station"),
                c("🚊","трамвай","tram"),
                c("🚁","вертолёт","helicopter"),
                c("🚟","подвесная дорога","suspension railway"),
                c("🚠","горная канатная дорога","mountain cableway"),
                c("🚡","канатная дорога","aerial tramway"),
                c("🛸","НЛО летающая тарелка","flying saucer ufo"),
                c("✈️","самолёт","airplane"),
                c("🛩️","лёгкий самолёт","small airplane"),
                c("🛫","взлёт самолёт","airplane departure"),
                c("🛬","посадка самолёт","airplane arrival"),
                c("🪂","парашют","parachute"),
                c("💺","кресло самолёт","seat"),
                c("🚀","ракета","rocket"),
                c("🛰️","спутник","satellite"),
                c("⛵","парусник","sailboat"),
                c("🚤","моторная лодка","speedboat"),
                c("🛥️","катер","motor boat"),
                c("🛳️","пассажирский корабль","passenger ship"),
                c("⛴️","паром","ferry"),
                c("🚢","корабль","ship"),
                c("⚓","якорь","anchor"),
                c("🪝","крюк","hook"),
                c("⛽","заправка","fuel pump"),
                c("🚧","дорожные работы","construction"),
                c("🚦","светофор","vertical traffic light"),
                c("🚥","горизонтальный светофор","horizontal traffic light"),
            ]
        },
        {
            "label": "Здания и места",
            "labelEn": "Buildings & places",
            "chars": [
                c("🏠","дом","house"),
                c("🏡","дом с садом","house garden"),
                c("🏢","офис здание","office building"),
                c("🏣","японский офис","japanese post office"),
                c("🏤","почта","post office"),
                c("🏥","больница","hospital"),
                c("🏦","банк","bank"),
                c("🏨","гостиница отель","hotel"),
                c("🏩","отель любви","love hotel"),
                c("🏪","магазин","convenience store"),
                c("🏫","школа","school"),
                c("🏬","торговый центр","department store"),
                c("🏭","завод фабрика","factory"),
                c("🏯","замок японский","japanese castle"),
                c("🏰","замок европейский","castle"),
                c("💒","свадьба","wedding"),
                c("🗼","токийская башня","tokyo tower"),
                c("🗽","статуя свободы","statue liberty"),
                c("⛪","церковь","church"),
                c("🕌","мечеть","mosque"),
                c("🛕","индуистский храм","hindu temple"),
                c("🕍","синагога","synagogue"),
                c("⛩️","тории","shinto shrine"),
                c("🕋","кааба","kaaba"),
                c("⛲","фонтан","fountain"),
                c("⛺","палатка","tent"),
                c("🌁","туман","foggy"),
                c("🌃","ночной город","night stars"),
                c("🏙️","городской пейзаж","cityscape"),
                c("🌄","рассвет горы","sunrise mountains"),
                c("🌅","рассвет","sunrise"),
                c("🌆","закат город","cityscape sunset"),
                c("🌇","закат","sunset"),
                c("🌉","ночной мост","bridge night"),
                c("🗾","карта японии","map japan"),
                c("🎑","луна над горами","moon viewing ceremony"),
                c("🏔️","заснеженная гора","snow capped mountain"),
                c("⛰️","гора","mountain"),
                c("🌋","вулкан","volcano"),
                c("🗻","гора Фудзи","mount fuji"),
                c("🏕️","кемпинг","camping"),
                c("🏖️","пляж","beach umbrella"),
                c("🏜️","пустыня","desert"),
                c("🏝️","необитаемый остров","desert island"),
                c("🏞️","национальный парк","national park"),
                c("🏟️","стадион","stadium"),
                c("🏛️","здание колонны","classical building"),
                c("🏗️","строительство","building construction"),
                c("🧱","кирпич","bricks"),
                c("🪨","камень","rock"),
                c("🪵","брёвна","wood"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 6. АКТИВНОСТИ И СПОРТ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "activities",
    "label": "Активности",
    "labelEn": "Activities",
    "icon": "⚽",
    "subgroups": [
        {
            "label": "Спорт",
            "labelEn": "Sports",
            "chars": [
                c("⚽","футбол","soccer ball"),
                c("🏀","баскетбол","basketball"),
                c("🏈","американский футбол","american football"),
                c("⚾","бейсбол","baseball"),
                c("🥎","софтбол","softball"),
                c("🎾","теннис","tennis"),
                c("🏐","волейбол","volleyball"),
                c("🏉","регби","rugby football"),
                c("🥏","фрисби","flying disc"),
                c("🎱","бильярд","pool 8 ball"),
                c("🏓","пинг-понг","ping pong"),
                c("🏸","бадминтон","badminton"),
                c("🏒","хоккей","ice hockey"),
                c("🏑","хоккей на траве","field hockey"),
                c("🥍","лакросс","lacrosse"),
                c("🏏","крикет","cricket game"),
                c("🪃","бумеранг","boomerang"),
                c("🥅","ворота","goal net"),
                c("⛳","гольф","flag in hole"),
                c("🪁","лук стрелы","bow arrow archery"),
                c("🎣","рыбалка","fishing pole"),
                c("🤿","дайвинг маска","diving mask"),
                c("🥊","боксёрские перчатки","boxing gloves"),
                c("🥋","кимоно карате","martial arts uniform"),
                c("🎽","спортивная майка","running shirt"),
                c("🛷","сани","sled"),
                c("🛷","сани","sled"),
                c("🥌","камень кёрлинга","curling stone"),
                c("⛷️","горные лыжи","skier"),
                c("🏂","сноуборд","snowboarder"),
                c("🪂","парашют","parachute"),
                c("🏋️","тяжёлая атлетика","person lifting weights"),
                c("🤼","борьба","people wrestling"),
                c("🤸","гимнастика","person cartwheeling"),
                c("⛹️","баскетболист","person bouncing ball"),
                c("🤺","фехтование","person fencing"),
                c("🏇","конные скачки","horse racing"),
                c("🧘","медитация йога","person lotus position"),
                c("🏊","плавание","person swimming"),
                c("🤽","водное поло","person playing water polo"),
                c("🚣","гребля","person rowing boat"),
                c("🧗","скалолазание","person climbing"),
                c("🚵","горный велосипед","person mountain biking"),
                c("🚴","велосипедист","person biking"),
                c("🏆","трофей кубок","trophy"),
                c("🥇","золотая медаль","1st place medal"),
                c("🥈","серебряная медаль","2nd place medal"),
                c("🥉","бронзовая медаль","3rd place medal"),
                c("🏅","медаль","sports medal"),
                c("🎖️","военная медаль","military medal"),
                c("🎗️","лента","reminder ribbon"),
                c("🎫","билет","ticket"),
                c("🎟️","входной билет","admission tickets"),
                c("🎪","цирк","circus tent"),
            ]
        },
        {
            "label": "Игры и развлечения",
            "labelEn": "Games & entertainment",
            "chars": [
                c("🎮","игровой контроллер","video game controller"),
                c("🕹️","джойстик","joystick"),
                c("🎲","кубик","die"),
                c("♟️","шахматная фигура","chess pawn"),
                c("🎯","мишень дартс","bullseye"),
                c("🎳","боулинг","bowling"),
                c("🎰","игровой автомат","slot machine"),
                c("🎭","театр маски","performing arts"),
                c("🎨","художник палитра","artist palette"),
                c("🧩","пазл","puzzle piece"),
                c("🪀","йо-йо","yo-yo"),
                c("🪁","лук стрелы","bow arrow"),
                c("🪆","матрёшка","nesting dolls"),
                c("🧸","медвежонок плюшевый","teddy bear"),
                c("🪅","пиньята","pinata"),
                c("🪩","диско шар","mirror ball"),
                c("🪄","волшебная палочка","magic wand"),
                c("🎭","театр","performing arts"),
                c("🎬","хлопушка кино","clapper board"),
                c("🎤","микрофон","microphone"),
                c("🎧","наушники","headphone"),
                c("🎼","ноты музыка","musical score"),
                c("🎵","нота","musical note"),
                c("🎶","ноты","musical notes"),
                c("🎷","саксофон","saxophone"),
                c("🪗","аккордеон","accordion"),
                c("🎸","гитара","guitar"),
                c("🎹","пианино","musical keyboard"),
                c("🎺","труба","trumpet"),
                c("🎻","скрипка","violin"),
                c("🪕","банджо","banjo"),
                c("🥁","барабан","drum"),
                c("🪘","конга барабан","long drum"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 7. ПРЕДМЕТЫ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "objects",
    "label": "Предметы",
    "labelEn": "Objects",
    "icon": "💡",
    "subgroups": [
        {
            "label": "Одежда и аксессуары",
            "labelEn": "Clothing",
            "chars": [
                c("👓","очки","glasses"),
                c("🕶️","тёмные очки","sunglasses"),
                c("🥽","защитные очки","goggles"),
                c("🦺","жилет безопасности","safety vest"),
                c("👔","галстук рубашка","necktie"),
                c("👕","футболка","t-shirt"),
                c("👖","джинсы","jeans"),
                c("🧣","шарф","scarf"),
                c("🧤","перчатки","gloves"),
                c("🧥","пальто","coat"),
                c("🧦","носки","socks"),
                c("👗","платье","dress"),
                c("👘","кимоно","kimono"),
                c("🥻","сари","sari"),
                c("🩱","купальник слитный","one piece swimsuit"),
                c("🩲","нижнее бельё","briefs"),
                c("🩳","шорты","shorts"),
                c("👙","бикини","bikini"),
                c("👚","женская одежда","womans clothes"),
                c("👛","кошелёк","purse"),
                c("👜","сумка","handbag"),
                c("👝","клатч","clutch bag"),
                c("🛍️","пакет покупки","shopping bags"),
                c("🎒","рюкзак","backpack"),
                c("🧳","чемодан","luggage"),
                c("👒","шляпа","womans hat"),
                c("🎩","цилиндр шляпа","top hat"),
                c("🧢","кепка бейсболка","billed cap"),
                c("🪖","военная каска","military helmet"),
                c("⛑️","спасательная каска","rescue workers helmet"),
                c("💄","помада","lipstick"),
                c("💍","кольцо","ring"),
                c("💎","бриллиант","gem stone"),
                c("👠","туфля","high heeled shoe"),
                c("👡","туфля женская","womans sandal"),
                c("🩰","балетки","ballet shoes"),
                c("👢","сапог","womans boot"),
                c("🥾","ботинок","hiking boot"),
                c("🥿","мокасин","flat shoe"),
                c("👟","кроссовок","running shoe"),
                c("🩴","вьетнамки","thong sandal"),
            ]
        },
        {
            "label": "Технологии",
            "labelEn": "Technology",
            "chars": [
                c("📱","смартфон телефон","mobile phone"),
                c("💻","ноутбук","laptop"),
                c("🖥️","монитор","desktop computer"),
                c("🖨️","принтер","printer"),
                c("⌨️","клавиатура","keyboard"),
                c("🖱️","мышь компьютерная","computer mouse"),
                c("🖲️","трекбол","trackball"),
                c("💽","диск дискета","computer disk"),
                c("💾","дискета","floppy disk"),
                c("💿","компакт-диск","optical disk"),
                c("📀","DVD","dvd"),
                c("🧮","счёты калькулятор","abacus"),
                c("📷","фотоаппарат","camera"),
                c("📸","фотоаппарат вспышка","camera flash"),
                c("📹","видеокамера","video camera"),
                c("🎥","кинокамера","movie camera"),
                c("📽️","кинопроектор","film projector"),
                c("📞","телефонная трубка","telephone receiver"),
                c("☎️","телефон","telephone"),
                c("📟","пейджер","pager"),
                c("📠","факс","fax machine"),
                c("📺","телевизор","television"),
                c("📻","радио","radio"),
                c("🎙️","студийный микрофон","studio microphone"),
                c("🎚️","слайдер уровень","level slider"),
                c("🎛️","пульт управления","control knobs"),
                c("🧭","компас","compass"),
                c("⏱️","секундомер","stopwatch"),
                c("⏲️","таймер","timer clock"),
                c("⏰","будильник","alarm clock"),
                c("🕰️","каминные часы","mantelpiece clock"),
                c("⌚","наручные часы","watch"),
                c("🔋","батарейка","battery"),
                c("🪫","разряженная батарея","low battery"),
                c("🔌","вилка розетка","electric plug"),
                c("💡","лампочка идея","light bulb"),
                c("🔦","фонарик","flashlight"),
                c("🕯️","свеча","candle"),
                c("🪔","масляная лампа","diya lamp"),
            ]
        },
        {
            "label": "Офис и учёба",
            "labelEn": "Office & school",
            "chars": [
                c("📝","записка блокнот","memo"),
                c("📄","страница","page facing up"),
                c("📃","свиток","page curl"),
                c("📑","закладки","bookmark tabs"),
                c("🗒️","блокнот","spiral notepad"),
                c("🗓️","отрывной календарь","spiral calendar"),
                c("📆","отрывной календарь","tear-off calendar"),
                c("📅","календарь","calendar"),
                c("🗑️","мусорное ведро","wastebasket"),
                c("📁","папка","file folder"),
                c("📂","открытая папка","open file folder"),
                c("🗂️","картотека","card index dividers"),
                c("📊","диаграмма график","bar chart"),
                c("📈","график роста","chart increasing"),
                c("📉","график падения","chart decreasing"),
                c("🗃️","картотека","card file box"),
                c("🗄️","шкаф с ящиками","file cabinet"),
                c("📋","буфер обмена","clipboard"),
                c("📌","кнопка","pushpin"),
                c("📍","кнопка закреплённая","round pushpin"),
                c("📎","скрепка","paperclip"),
                c("🖇️","скрепки","linked paperclips"),
                c("📏","линейка","straight ruler"),
                c("📐","угольник","triangular ruler"),
                c("✂️","ножницы","scissors"),
                c("🗃️","картотека","card file box"),
                c("✒️","ручка перьевая","black nib"),
                c("🖊️","ручка","pen"),
                c("🖋️","перьевая ручка","fountain pen"),
                c("🖌️","кисть","paintbrush"),
                c("🖍️","мелок","crayon"),
                c("📌","кнопка","pushpin"),
                c("🔍","лупа поиск","magnifying glass left"),
                c("🔎","лупа","magnifying glass right"),
            ]
        },
        {
            "label": "Инструменты",
            "labelEn": "Tools",
            "chars": [
                c("🔧","гаечный ключ","wrench"),
                c("🪛","отвёртка","screwdriver"),
                c("🔨","молоток","hammer"),
                c("⚒️","скрещённые молотки","hammer pick"),
                c("🛠️","молоток и ключ","hammer wrench"),
                c("⛏️","кирка","pick"),
                c("⚙️","шестерня","gear"),
                c("🗜️","струбцина","clamp"),
                c("⚖️","весы","balance scale"),
                c("🦯","трость","white cane"),
                c("🔗","цепь звено","link"),
                c("⛓️","цепь","chains"),
                c("🪝","крюк","hook"),
                c("🧲","магнит","magnet"),
                c("🔑","ключ","key"),
                c("🗝️","старый ключ","old key"),
                c("🔒","замок закрытый","locked"),
                c("🔓","замок открытый","unlocked"),
                c("🚪","дверь","door"),
                c("🪞","зеркало","mirror"),
                c("🪟","окно","window"),
                c("🛋️","диван","couch lamp"),
                c("🪑","стул","chair"),
                c("🚿","душ","shower"),
                c("🛁","ванна","bathtub"),
                c("🪠","вантуз","plunger"),
                c("🧴","флакон","lotion bottle"),
                c("🪥","зубная щётка","toothbrush"),
                c("🧹","метла","broom"),
                c("🧺","корзина","basket"),
                c("🧻","туалетная бумага","roll of paper"),
                c("🪣","ведро","bucket"),
                c("🧼","мыло","soap"),
                c("🫧","пузыри мыльные","bubbles"),
                c("🪒","бритва","razor"),
                c("💊","таблетка","pill"),
                c("💉","шприц","syringe"),
                c("🩸","кровь","drop of blood"),
                c("🩹","пластырь","adhesive bandage"),
                c("🩺","стетоскоп","stethoscope"),
                c("🩻","рентген","x-ray"),
                c("🔬","микроскоп","microscope"),
                c("🔭","телескоп","telescope"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 8. СИМВОЛЫ ЭМОДЗИ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "symbols_emo",
    "label": "Символы",
    "labelEn": "Symbols",
    "icon": "❤️",
    "subgroups": [
        {
            "label": "Сердца",
            "labelEn": "Hearts",
            "chars": [
                c("❤️","красное сердце","red heart"),
                c("🧡","оранжевое сердце","orange heart"),
                c("💛","жёлтое сердце","yellow heart"),
                c("💚","зелёное сердце","green heart"),
                c("💙","синее сердце","blue heart"),
                c("🩵","голубое сердце","light blue heart"),
                c("💜","фиолетовое сердце","purple heart"),
                c("🖤","чёрное сердце","black heart"),
                c("🩶","серое сердце","grey heart"),
                c("🤍","белое сердце","white heart"),
                c("🤎","коричневое сердце","brown heart"),
                c("💔","разбитое сердце","broken heart"),
                c("❤️‍🔥","горящее сердце","heart on fire"),
                c("❤️‍🩹","сердце с пластырем","mending heart"),
                c("❣️","восклицательный знак сердце","heart exclamation"),
                c("💕","два сердца","two hearts"),
                c("💞","вращающиеся сердца","revolving hearts"),
                c("💓","бьющееся сердце","beating heart"),
                c("💗","растущее сердце","growing heart"),
                c("💖","сверкающее сердце","sparkling heart"),
                c("💘","сердце со стрелой","heart arrow"),
                c("💝","сердце с лентой","heart ribbon"),
                c("💟","сердечко украшение","heart decoration"),
                c("☮️","мир","peace symbol"),
                c("✝️","крест христианский","latin cross"),
                c("☦️","православный крест","orthodox cross"),
                c("🕎","менора","menorah"),
                c("🔯","звезда Давида","dotted six pointed star"),
                c("☸️","колесо дхармы","wheel of dharma"),
                c("☯️","инь-ян","yin yang"),
                c("☪️","луна со звездой","star and crescent"),
                c("🛐","место для молитвы","place of worship"),
                c("⚛️","атом","atom symbol"),
                c("🉑","кан японский","japanese acceptable button"),
                c("☑️","галочка в квадрате","check box check"),
                c("✅","зелёная галочка","check mark button"),
                c("❎","крест в квадрате","cross mark button"),
                c("🆗","ОК кнопка","ok button"),
                c("🆙","UP кнопка","up button"),
                c("🆕","NEW новый","new button"),
                c("🆓","FREE бесплатно","free button"),
                c("🆒","COOL круто","cool button"),
                c("🆖","NG кнопка","ng button"),
                c("🆘","SOS помощь","sos button"),
            ]
        },
        {
            "label": "Звёзды и огни",
            "labelEn": "Stars & lights",
            "chars": [
                c("⭐","звезда","star"),
                c("🌟","сияющая звезда","glowing star"),
                c("✨","блёстки искры","sparkles"),
                c("💫","кружится звезда","dizzy star"),
                c("⚡","молния","lightning high voltage"),
                c("🔥","огонь пламя","fire"),
                c("🌈","радуга","rainbow"),
                c("💥","взрыв","collision explosion"),
                c("💢","злость символ","anger symbol"),
                c("💬","пузырь речи сообщение","speech balloon"),
                c("💭","мысли","thought balloon"),
                c("💤","спать Zzzz","zzz sleep"),
                c("🎆","фейерверк","fireworks"),
                c("🎇","бенгальский огонь","sparkler"),
                c("🧨","петарда","firecracker"),
                c("✡️","звезда Давида","star of david"),
                c("💠","ромб с точкой","diamond blue"),
                c("🔶","большой оранжевый ромб","large orange diamond"),
                c("🔷","большой синий ромб","large blue diamond"),
                c("🔸","малый оранжевый ромб","small orange diamond"),
                c("🔹","малый синий ромб","small blue diamond"),
                c("🔺","красный треугольник вверх","red triangle up"),
                c("🔻","красный треугольник вниз","red triangle down"),
                c("💲","знак доллара","heavy dollar sign"),
                c("❗","восклицательный знак","exclamation mark"),
                c("❓","вопросительный знак","question mark"),
                c("‼️","двойной восклицательный","double exclamation"),
                c("⁉️","восклицательный и вопросительный","exclamation question"),
                c("🔅","уменьшить яркость","dim button"),
                c("🔆","увеличить яркость","bright button"),
            ]
        },
        {
            "label": "Знаки и кнопки",
            "labelEn": "Signs & buttons",
            "chars": [
                c("🚫","запрещено","prohibited"),
                c("⛔","стоп","no entry"),
                c("🚳","велосипеды запрещены","no bicycles"),
                c("🚭","курение запрещено","no smoking"),
                c("🚯","мусор нельзя","no littering"),
                c("🚱","не питьевая вода","non potable water"),
                c("🚷","пешеходы запрещены","no pedestrians"),
                c("📵","телефон запрещён","no mobile phones"),
                c("🔞","только для взрослых","no one under 18"),
                c("☢️","радиоактивно","radioactive"),
                c("☣️","биологическая опасность","biohazard"),
                c("⬆️","вверх стрелка","up arrow"),
                c("↗️","вверх вправо стрелка","up right arrow"),
                c("➡️","вправо стрелка","right arrow"),
                c("↘️","вниз вправо","down right arrow"),
                c("⬇️","вниз стрелка","down arrow"),
                c("↙️","вниз влево","down left arrow"),
                c("⬅️","влево стрелка","left arrow"),
                c("↖️","вверх влево","up left arrow"),
                c("↕️","вверх вниз стрелка","up down arrow"),
                c("↔️","вправо влево стрелка","left right arrow"),
                c("↩️","поворот влево","right arrow curving left"),
                c("↪️","поворот вправо","left arrow curving right"),
                c("⤴️","изогнутая стрелка вверх","right arrow curving up"),
                c("⤵️","изогнутая стрелка вниз","right arrow curving down"),
                c("🔃","вращение по часовой","clockwise vertical arrows"),
                c("🔄","вращение против часовой","counterclockwise arrows"),
                c("🔙","назад","back arrow"),
                c("🔚","конец","end arrow"),
                c("🔛","вкл","on arrow"),
                c("🔜","скоро","soon arrow"),
                c("🔝","топ","top arrow"),
                c("🛐","молитва","place worship"),
                c("⚜️","лилия","fleur de lis"),
                c("🔱","трезубец","trident emblem"),
                c("📛","бейдж имя","name badge"),
                c("🔰","зелёный ромб","japanese symbol beginner"),
                c("♻️","переработка","recycling symbol"),
                c("✅","галочка","check mark"),
                c("🈯","японский символ","japanese reserved button"),
                c("💹","иена рост","chart increasing yen"),
                c("❇️","снежинка стиль","sparkle"),
                c("✳️","восьмиконечная звезда","eight spoked asterisk"),
                c("❎","крест","cross mark button"),
                c("🌐","глобус","globe meridians"),
                c("💠","ромб","diamond blue"),
                c("Ⓜ️","метро","circled m"),
                c("🌀","вихрь","cyclone"),
                c("💤","сон","zzz"),
                c("🏧","банкомат ATM","atm sign"),
                c("🚾","туалет","water closet"),
                c("♿","инвалидное кресло","wheelchair symbol"),
                c("🅿️","парковка","p button"),
                c("🛗","лифт","elevator"),
                c("🈳","японский свободно","japanese free of charge button"),
                c("🈹","японский скидка","japanese discount button"),
                c("🈚","японский бесплатно","japanese free of charge button"),
                c("🈲","японский запрещено","japanese prohibited button"),
                c("🉐","японский выгодно","japanese bargain button"),
                c("🈶","японский занято","japanese not free of charge button"),
                c("🈷️","японский ежемесячный","japanese monthly amount button"),
                c("🈸","японский заявление","japanese application button"),
                c("🈴","японский проходной балл","japanese passing grade button"),
                c("🈵","японский нет вакансий","japanese no vacancy button"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 9. СТРЕЛКИ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "arrows",
    "label": "Стрелки",
    "labelEn": "Arrows",
    "icon": "→",
    "subgroups": [
        {
            "label": "Одиночные",
            "labelEn": "Single arrows",
            "chars": [
                c("→","вправо right arrow","→"),
                c("←","влево left arrow","←"),
                c("↑","вверх up arrow","↑"),
                c("↓","вниз down arrow","↓"),
                c("↗","вправо вверх arrow upper right","↗"),
                c("↘","вправо вниз arrow lower right","↘"),
                c("↙","влево вниз arrow lower left","↙"),
                c("↖","влево вверх arrow upper left","↖"),
                c("↔","горизонтальная двойная horizontal double arrow","↔"),
                c("↕","вертикальная double arrow","↕"),
                c("↩","поворот стрелка return arrow","↩"),
                c("↪","поворот вправо steer arrow","↪"),
                c("⤴","изогнута вверх curved arrow up","⤴"),
                c("⤵","изогнута вниз curved arrow down","⤵"),
                c("↰","повернуть влево turn left arrow","↰"),
                c("↱","повернуть вправо turn right arrow","↱"),
                c("⇐","двойная влево double left arrow","⇐"),
                c("⇒","двойная вправо double right arrow","⇒"),
                c("⇑","двойная вверх double up arrow","⇑"),
                c("⇓","двойная вниз double down arrow","⇓"),
                c("⇔","двойная горизонтальная double horizontal arrow","⇔"),
                c("⇕","двойная вертикальная double vertical arrow","⇕"),
            ]
        },
        {
            "label": "Жирные и стилизованные",
            "labelEn": "Bold & styled",
            "chars": [
                c("➡","жирная вправо bold right arrow","➡"),
                c("⬅","жирная влево bold left arrow","⬅"),
                c("⬆","жирная вверх bold up arrow","⬆"),
                c("⬇","жирная вниз bold down arrow","⬇"),
                c("➢","наконечник вправо arrowhead right","➢"),
                c("➤","треугольник вправо triangle right","➤"),
                c("▶","треугольник play вправо play button","▶"),
                c("◀","треугольник влево left triangle","◀"),
                c("▲","треугольник вверх up triangle","▲"),
                c("▼","треугольник вниз down triangle","▼"),
                c("►","вправо play right-pointing small","►"),
                c("◄","влево left-pointing small","◄"),
                c("▸","малый вправо right small triangle","▸"),
                c("◂","малый влево left small triangle","◂"),
                c("▴","малый вверх up small triangle","▴"),
                c("▾","малый вниз down small triangle","▾"),
                c("⟶","длинная вправо long right arrow","⟶"),
                c("⟵","длинная влево long left arrow","⟵"),
                c("⟷","длинная горизонтальная long horizontal arrow","⟷"),
                c("⟹","двойная длинная вправо long double right arrow","⟹"),
                c("⟸","двойная длинная влево long double left arrow","⟸"),
                c("⟺","двойная длинная long double horizontal arrow","⟺"),
            ]
        },
        {
            "label": "Круговые и специальные",
            "labelEn": "Circular & special",
            "chars": [
                c("↻","по часовой clockwise arrow","↻"),
                c("↺","против часовой anticlockwise arrow","↺"),
                c("⟳","обновление clockwise open circle arrow","⟳"),
                c("⟲","против clockwise anticlockwise open circle","⟲"),
                c("↷","по часовой clockwise curve","↷"),
                c("↶","против часовой anticlockwise curve","↶"),
                c("⇄","вправо влево right left arrows","⇄"),
                c("⇆","влево вправо left right arrows","⇆"),
                c("⇅","вверх вниз up down arrows","⇅"),
                c("⇌","вправо влево equilibrium arrows","⇌"),
                c("⇋","влево вправо equilibrium reverse","⇋"),
                c("↭","влево вправо волна left right wave arrow","↭"),
                c("↬","петля loop arrow","↬"),
                c("⇜","волна влево leftwards wave arrow","⇜"),
                c("⇝","волна вправо rightwards wave arrow","⇝"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 10. МАТЕМАТИКА
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "math",
    "label": "Математика",
    "labelEn": "Math",
    "icon": "∑",
    "subgroups": [
        {
            "label": "Операторы",
            "labelEn": "Operators",
            "chars": [
                c("±","плюс минус plus minus","±"),
                c("×","умножение multiplication sign","×"),
                c("÷","деление division sign","÷"),
                c("≠","не равно not equal","≠"),
                c("≈","приблизительно approximately equal","≈"),
                c("≡","тождественно равно identical to","≡"),
                c("≤","меньше или равно less than equal","≤"),
                c("≥","больше или равно greater than equal","≥"),
                c("≪","много меньше much less than","≪"),
                c("≫","много больше much greater than","≫"),
                c("∝","пропорционально proportional to","∝"),
                c("∞","бесконечность infinity","∞"),
                c("∅","пустое множество empty set","∅"),
                c("∈","принадлежит element of","∈"),
                c("∉","не принадлежит not element of","∉"),
                c("∋","содержит contains as member","∋"),
                c("∩","пересечение intersection","∩"),
                c("∪","объединение union","∪"),
                c("⊂","подмножество subset of","⊂"),
                c("⊃","надмножество superset of","⊃"),
                c("⊆","подмножество или равно subset equal","⊆"),
                c("⊇","надмножество или равно superset equal","⊇"),
                c("∧","логическое и logical and","∧"),
                c("∨","логическое или logical or","∨"),
                c("¬","логическое отрицание negation","¬"),
                c("⊕","исключающее или xor exclusive or","⊕"),
                c("⊗","тензорное произведение tensor product","⊗"),
            ]
        },
        {
            "label": "Анализ и функции",
            "labelEn": "Calculus",
            "chars": [
                c("∑","сумма summation","∑"),
                c("∏","произведение product","∏"),
                c("∫","интеграл integral","∫"),
                c("∬","двойной интеграл double integral","∬"),
                c("∭","тройной интеграл triple integral","∭"),
                c("∮","контурный интеграл contour integral","∮"),
                c("∂","частная производная partial derivative","∂"),
                c("∇","набла nabla gradient","∇"),
                c("√","квадратный корень square root","√"),
                c("∛","кубический корень cube root","∛"),
                c("∜","корень четвёртой степени fourth root","∜"),
                c("ℕ","натуральные числа natural numbers","ℕ"),
                c("ℤ","целые числа integers","ℤ"),
                c("ℚ","рациональные числа rational numbers","ℚ"),
                c("ℝ","вещественные числа real numbers","ℝ"),
                c("ℂ","комплексные числа complex numbers","ℂ"),
                c("ℏ","постоянная Планка planck constant","ℏ"),
                c("ℓ","скрипт l script small l","ℓ"),
                c("℃","градус Цельсия degree celsius","℃"),
                c("℉","градус Фаренгейта degree fahrenheit","℉"),
                c("°","градус degree","°"),
                c("′","штрих prime минута","′"),
                c("″","двойной штрих double prime секунда","″"),
            ]
        },
        {
            "label": "Греческие буквы",
            "labelEn": "Greek letters",
            "chars": [
                c("α","альфа alpha","α"),
                c("β","бета beta","β"),
                c("γ","гамма gamma","γ"),
                c("δ","дельта delta","δ"),
                c("ε","эпсилон epsilon","ε"),
                c("ζ","дзета zeta","ζ"),
                c("η","эта eta","η"),
                c("θ","тета theta","θ"),
                c("ι","йота iota","ι"),
                c("κ","каппа kappa","κ"),
                c("λ","лямбда lambda","λ"),
                c("μ","мю mu","μ"),
                c("ν","ню nu","ν"),
                c("ξ","кси xi","ξ"),
                c("π","пи pi","π"),
                c("ρ","ро rho","ρ"),
                c("σ","сигма sigma","σ"),
                c("τ","тау tau","τ"),
                c("υ","ипсилон upsilon","υ"),
                c("φ","фи phi","φ"),
                c("χ","хи chi","χ"),
                c("ψ","пси psi","ψ"),
                c("ω","омега omega","ω"),
                c("Γ","Гамма Gamma","Γ"),
                c("Δ","Дельта Delta","Δ"),
                c("Θ","Тета Theta","Θ"),
                c("Λ","Лямбда Lambda","Λ"),
                c("Π","Пи Pi","Π"),
                c("Σ","Сигма Sigma","Σ"),
                c("Φ","Фи Phi","Φ"),
                c("Ψ","Пси Psi","Ψ"),
                c("Ω","Омега Omega","Ω"),
            ]
        },
        {
            "label": "Дроби и надстрочные",
            "labelEn": "Fractions & superscript",
            "chars": [
                c("½","одна вторая one half","½"),
                c("⅓","одна треть one third","⅓"),
                c("¼","одна четвёртая one quarter","¼"),
                c("¾","три четвёртых three quarters","¾"),
                c("⅛","одна восьмая one eighth","⅛"),
                c("⅜","три восьмых three eighths","⅜"),
                c("⅝","пять восьмых five eighths","⅝"),
                c("⅞","семь восьмых seven eighths","⅞"),
                c("⅕","одна пятая one fifth","⅕"),
                c("⅖","две пятых two fifths","⅖"),
                c("⅗","три пятых three fifths","⅗"),
                c("⅘","четыре пятых four fifths","⅘"),
                c("⁰","ноль надстрочный superscript zero","⁰"),
                c("¹","один надстрочный superscript one","¹"),
                c("²","квадрат superscript two","²"),
                c("³","куб superscript three","³"),
                c("⁴","надстрочный четыре superscript four","⁴"),
                c("⁵","надстрочный пять superscript five","⁵"),
                c("⁶","надстрочный шесть superscript six","⁶"),
                c("⁷","надстрочный семь superscript seven","⁷"),
                c("⁸","надстрочный восемь superscript eight","⁸"),
                c("⁹","надстрочный девять superscript nine","⁹"),
                c("⁺","надстрочный плюс superscript plus","⁺"),
                c("⁻","надстрочный минус superscript minus","⁻"),
                c("⁽","надстрочная скобка superscript parenthesis","⁽"),
                c("⁾","надстрочная скобка superscript parenthesis","⁾"),
                c("₀","нижний ноль subscript zero","₀"),
                c("₁","нижний один subscript one","₁"),
                c("₂","нижний два subscript two","₂"),
                c("₃","нижний три subscript three","₃"),
                c("₄","нижний четыре subscript four","₄"),
                c("₅","нижний пять subscript five","₅"),
                c("₆","нижний шесть subscript six","₆"),
                c("₇","нижний семь subscript seven","₇"),
                c("₈","нижний восемь subscript eight","₈"),
                c("₉","нижний девять subscript nine","₉"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 11. ТИПОГРАФИКА
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "typography",
    "label": "Типографика",
    "labelEn": "Typography",
    "icon": "«",
    "subgroups": [
        {
            "label": "Кавычки",
            "labelEn": "Quotation marks",
            "chars": [
                c("\u00AB","ёлочки левая french guillemet left","«"),
                c("\u00BB","ёлочки правая french guillemet right","»"),
                c("\u201E","немецкая открывающая german lower quotation","„"),
                c("\u201C","двойная левая double quotation left","\u201C"),
                c("\u201D","двойная правая double quotation right","\u201D"),
                c("\u2018","одинарная левая single quotation left","\u2018"),
                c("\u2019","одинарная правая апостроф single quotation right apostrophe","\u2019"),
                c("\u201A","немецкая одинарная lower single quotation","\u201A"),
                c("\u2039","одинарный угол левая single guillemet left","\u2039"),
                c("\u203A","одинарный угол правая single guillemet right","\u203A"),
                c("\u201B","перевёрнутая открывающая reversed quotation","\u201B"),
                c("\u201F","перевёрнутая двойная reversed double quotation","\u201F"),
            ]
        },
        {
            "label": "Тире и дефис",
            "labelEn": "Dashes",
            "chars": [
                c("\u2014","тире em dash","—"),
                c("\u2013","короткое тире en dash","–"),
                c("\u2012","цифровое тире figure dash","\u2012"),
                c("\u2015","горизонтальная черта horizontal bar","\u2015"),
                c("\u2010","дефис hyphen","\u2010"),
                c("\u2011","неразрывный дефис non breaking hyphen","\u2011"),
                c("\u00AD","мягкий перенос soft hyphen","\u00AD"),
                c("~","тильда тиральдо tilde","~"),
            ]
        },
        {
            "label": "Пунктуация и знаки",
            "labelEn": "Punctuation",
            "chars": [
                c("\u2026","многоточие ellipsis","…"),
                c("\u00B7","средняя точка middle dot interpunct","\u00B7"),
                c("\u2022","маркер список bullet","•"),
                c("\u2023","треугольный маркер triangle bullet","\u2023"),
                c("\u2043","дефис маркер hyphen bullet","\u2043"),
                c("\u204B","перевёрнутый знак абзаца reversed pilcrow","\u204B"),
                c("\u00B6","знак абзаца pilcrow paragraph","\u00B6"),
                c("\u00A7","параграф section sign","\u00A7"),
                c("\u2020","крест кинжал dagger","\u2020"),
                c("\u2021","двойной крест double dagger","\u2021"),
                c("\u2032","штрих минута prime","\u2032"),
                c("\u2033","двойной штрих секунда double prime","\u2033"),
                c("\u203D","интеробанг interrobang","\u203D"),
                c("!","восклицательный знак exclamation","!"),
                c("?","вопросительный знак question","?"),
                c("\u00BF","перевёрнутый вопрос inverted question","\u00BF"),
                c("\u00A1","перевёрнутый восклицательный inverted exclamation","\u00A1"),
            ]
        },
        {
            "label": "Специальные знаки",
            "labelEn": "Special signs",
            "chars": [
                c("\u00A9","авторское право copyright","©"),
                c("\u00AE","зарегистрированный товарный знак registered trademark","®"),
                c("\u2122","торговая марка trademark","™"),
                c("\u2117","знак звукозаписи sound recording copyright","\u2117"),
                c("\u2120","знак обслуживания service mark","\u2120"),
                c("\u00B0","градус degree","°"),
                c("\u2030","промилле per mille sign","\u2030"),
                c("\u2031","базисный пункт per ten thousand","\u2031"),
                c("\u00B5","микро micro sign","µ"),
                c("\u2116","номер number sign","№"),
                c("\u0023","хэштег решётка hash number sign","#"),
                c("\u0026","амперсанд ampersand","&"),
                c("\u002A","звёздочка asterisk","*"),
                c("\u0040","собака at sign","@"),
                c("\u005C","обратный слеш backslash","\\"),
                c("\u007C","вертикальная черта pipe vertical bar","|"),
                c("\u00A6","разорванная черта broken bar","\u00A6"),
                c("\u2016","двойная вертикальная double vertical line","\u2016"),
            ]
        },
        {
            "label": "Скобки",
            "labelEn": "Brackets",
            "chars": [
                c("⟨","угловая скобка левая angle bracket left","⟨"),
                c("⟩","угловая скобка правая angle bracket right","⟩"),
                c("⌈","потолочная левая ceiling left","⌈"),
                c("⌉","потолочная правая ceiling right","⌉"),
                c("⌊","напольная левая floor left","⌊"),
                c("⌋","напольная правая floor right","⌋"),
                c("⦃","фигурная белая left white curly bracket","⦃"),
                c("⦄","фигурная белая правая right white curly bracket","⦄"),
                c("〔","скобка черепашья tortoise bracket left","〔"),
                c("〕","скобка черепашья правая tortoise bracket right","〕"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 12. ВАЛЮТЫ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "currency",
    "label": "Валюты",
    "labelEn": "Currency",
    "icon": "€",
    "subgroups": [
        {
            "label": "Основные",
            "labelEn": "Major currencies",
            "chars": [
                c("\u20AC","евро euro","€"),
                c("\u0024","доллар dollar","$"),
                c("\u00A3","фунт стерлингов pound sterling","£"),
                c("\u00A5","иена юань yen yuan","¥"),
                c("\u20BD","рубль ruble","₽"),
                c("\u20BF","биткоин bitcoin","₿"),
                c("\u20A3","французский франк french franc","\u20A3"),
                c("\u20A4","лира lira","\u20A4"),
                c("\u20A6","найра naira","\u20A6"),
                c("\u20A7","песета peseta","\u20A7"),
                c("\u20A8","рупия rupee","₨"),
                c("\u20A9","вона won","₩"),
                c("\u20AA","новый шекель new sheqel","₪"),
                c("\u20AB","донг dong","₫"),
                c("\u20AC","евро euro","€"),
                c("\u20AD","кип kip","\u20AD"),
                c("\u20AE","тугрик tugrik","₮"),
                c("\u20AF","драхма drachma","\u20AF"),
                c("\u20B0","германская пфенниг german penny","\u20B0"),
                c("\u20B1","песо peso","₱"),
                c("\u20B2","гуарани guarani","₲"),
                c("\u20B3","аустраль austral","₳"),
                c("\u20B4","гривна hryvnia","₴"),
                c("\u20B5","седи cedi","₵"),
                c("\u20B6","ливр tournois livre tournois","\u20B6"),
                c("\u20B7","спесмен spesmilo","\u20B7"),
                c("\u20B8","тенге tenge","₸"),
                c("\u20B9","индийская рупия indian rupee","₹"),
                c("\u20BA","лира турецкая turkish lira","₺"),
                c("\u20BB","северный путь nordic mark","\u20BB"),
                c("\u20BC","манат manat","₼"),
                c("\u20BE","лари lari","₾"),
                c("\u20BF","биткоин bitcoin","₿"),
                c("\u00A2","цент cent","¢"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 13. ДИАКРИТИКА
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "diacritics",
    "label": "Диакритика",
    "labelEn": "Diacritics",
    "icon": "À",
    "subgroups": [
        {
            "label": "A",
            "labelEn": "Letter A",
            "chars": [
                c("À","а с акутом a grave","À"),
                c("Á","а акут a acute","Á"),
                c("Â","а циркумфлекс a circumflex","Â"),
                c("Ã","а тильда a tilde","Ã"),
                c("Ä","а умлаут a umlaut","Ä"),
                c("Å","а кружок a ring","Å"),
                c("Æ","ae лигатура ae ligature","Æ"),
                c("à","а с акутом строчная a grave lower","à"),
                c("á","а акут строчная a acute lower","á"),
                c("â","а циркумфлекс строчная a circumflex lower","â"),
                c("ã","а тильда строчная a tilde lower","ã"),
                c("ä","а умлаут строчная a umlaut lower","ä"),
                c("å","а кружок строчная a ring lower","å"),
                c("æ","ae лигатура строчная ae ligature lower","æ"),
            ]
        },
        {
            "label": "C, E",
            "labelEn": "C, E",
            "chars": [
                c("Ç","c с седилью c cedilla","Ç"),
                c("ç","c с седилью строчная c cedilla lower","ç"),
                c("È","e акут a grave","È"),
                c("É","e острый e acute","É"),
                c("Ê","e циркумфлекс e circumflex","Ê"),
                c("Ë","e умлаут e umlaut","Ë"),
                c("è","e акут строчная e grave lower","è"),
                c("é","e острый строчная e acute lower","é"),
                c("ê","e циркумфлекс строчная e circumflex lower","ê"),
                c("ë","e умлаут строчная e umlaut lower","ë"),
            ]
        },
        {
            "label": "I, N, O",
            "labelEn": "I, N, O",
            "chars": [
                c("Ì","i акут i grave","Ì"),
                c("Í","i острый i acute","Í"),
                c("Î","i циркумфлекс i circumflex","Î"),
                c("Ï","i умлаут i umlaut","Ï"),
                c("ì","i акут строчная i grave lower","ì"),
                c("í","i острый строчная i acute lower","í"),
                c("î","i циркумфлекс строчная i circumflex lower","î"),
                c("ï","i умлаут строчная i umlaut lower","ï"),
                c("Ñ","n тильда n tilde","Ñ"),
                c("ñ","n тильда строчная n tilde lower","ñ"),
                c("Ò","o акут o grave","Ò"),
                c("Ó","o острый o acute","Ó"),
                c("Ô","o циркумфлекс o circumflex","Ô"),
                c("Õ","o тильда o tilde","Õ"),
                c("Ö","o умлаут o umlaut","Ö"),
                c("Ø","o перечёркнутая o slash","Ø"),
                c("Œ","oe лигатура oe ligature","Œ"),
                c("ò","o акут строчная o grave lower","ò"),
                c("ó","o острый строчная o acute lower","ó"),
                c("ô","o циркумфлекс строчная o circumflex lower","ô"),
                c("õ","o тильда строчная o tilde lower","õ"),
                c("ö","o умлаут строчная o umlaut lower","ö"),
                c("ø","o перечёркнутая строчная o slash lower","ø"),
                c("œ","oe лигатура строчная oe ligature lower","œ"),
            ]
        },
        {
            "label": "U, Y, другие",
            "labelEn": "U, Y, others",
            "chars": [
                c("Ù","u акут u grave","Ù"),
                c("Ú","u острый u acute","Ú"),
                c("Û","u циркумфлекс u circumflex","Û"),
                c("Ü","u умлаут u umlaut","Ü"),
                c("ù","u акут строчная u grave lower","ù"),
                c("ú","u острый строчная u acute lower","ú"),
                c("û","u циркумфлекс строчная u circumflex lower","û"),
                c("ü","u умлаут строчная u umlaut lower","ü"),
                c("Ý","y острый y acute","Ý"),
                c("Ÿ","y умлаут y umlaut","Ÿ"),
                c("ý","y острый строчная y acute lower","ý"),
                c("ÿ","y умлаут строчная y umlaut lower","ÿ"),
                c("ß","немецкое эсцет sharp s german eszett","ß"),
                c("Ð","исландское eth d stroke Ð","Ð"),
                c("ð","исландское eth строчная d stroke lower","ð"),
                c("Þ","исландское торн thorn Þ","Þ"),
                c("þ","исландское торн строчная thorn lower","þ"),
                c("Š","s с хачеком s caron","Š"),
                c("š","s с хачеком строчная s caron lower","š"),
                c("Ž","z с хачеком z caron","Ž"),
                c("ž","z с хачеком строчная z caron lower","ž"),
                c("Č","c с хачеком c caron","Č"),
                c("č","c с хачеком строчная c caron lower","č"),
                c("ě","e с хачеком строчная e caron lower","ě"),
                c("Ř","r с хачеком r caron","Ř"),
                c("ř","r с хачеком строчная r caron lower","ř"),
                c("ā","a с макроном a macron lower","ā"),
                c("ē","e с макроном e macron lower","ē"),
                c("ī","i с макроном i macron lower","ī"),
                c("ō","o с макроном o macron lower","ō"),
                c("ū","u с макроном u macron lower","ū"),
            ]
        },
    ]
})

# ────────────────────────────────────────────────────────────────────────────
# 14. СОБЫТИЯ И ПРАЗДНИКИ
# ────────────────────────────────────────────────────────────────────────────
GROUPS.append({
    "id": "events",
    "label": "Праздники",
    "labelEn": "Events",
    "icon": "🎉",
    "subgroups": [
        {
            "label": "Праздники",
            "labelEn": "Celebrations",
            "chars": [
                c("🎉","вечеринка конфетти party popper","party"),
                c("🎊","конфетти confetti ball","confetti"),
                c("🎈","воздушный шар birthday balloon","balloon"),
                c("🎀","лента бант ribbon","ribbon"),
                c("🎁","подарок present","gift"),
                c("🎗️","лента напоминание reminder ribbon","reminder"),
                c("🎟️","билет admission ticket","ticket"),
                c("🎫","билет ticket","ticket"),
                c("🎖️","медаль medal","medal"),
                c("🏆","кубок trophy","trophy"),
                c("🥇","золото gold medal","gold"),
                c("🥈","серебро silver medal","silver"),
                c("🥉","бронза bronze medal","bronze"),
                c("⚽","мяч ball","ball"),
                c("🏅","спортивная медаль sports medal","sports medal"),
                c("🎪","цирк circus tent","circus"),
                c("🤹","жонглёр juggling","juggling"),
                c("🎭","театр performing arts","theater"),
                c("🎨","искусство artist palette","art"),
                c("🖼️","картина picture frame","picture"),
                c("🎬","кино clapper board","movie"),
                c("🎤","концерт microphone","microphone"),
                c("🎧","музыка headphone","headphones"),
                c("🎼","ноты musical score","musical"),
                c("🎆","фейерверк fireworks","fireworks"),
                c("🎇","бенгальский огонь sparkler","sparkler"),
                c("🧨","петарда firecracker","firecracker"),
                c("✨","блёстки sparkles","sparkles"),
                c("🎑","любование луной moon viewing","moon viewing"),
                c("🎃","хэллоуин тыква halloween pumpkin","halloween"),
                c("🎄","ёлка christmas tree","christmas"),
                c("🎋","бамбук tanabata tree","tanabata"),
                c("🎍","новый год bamboo","bamboo"),
                c("🎎","куклы japanese dolls","japanese dolls"),
                c("🎏","карп koinobori","koinobori"),
                c("🎐","ветряной колокольчик wind chime","wind chime"),
                c("🧧","конверт с деньгами red envelope","red envelope"),
                c("🪅","пиньята pinata","pinata"),
                c("🪆","матрёшка nesting dolls","nesting dolls"),
                c("🎠","карусель carousel horse","carousel"),
                c("🎡","колесо обозрения ferris wheel","ferris wheel"),
                c("🎢","американские горки roller coaster","roller coaster"),
                c("🎯","мишень bullseye","bullseye"),
                c("🎲","кубик dice","dice"),
            ]
        },
        {
            "label": "Время и часы",
            "labelEn": "Time & clocks",
            "chars": [
                c("🕐","час один o clock one","🕐"),
                c("🕑","два часа two o clock","🕑"),
                c("🕒","три часа three o clock","🕒"),
                c("🕓","четыре часа four o clock","🕓"),
                c("🕔","пять часов five o clock","🕔"),
                c("🕕","шесть часов six o clock","🕕"),
                c("🕖","семь часов seven o clock","🕖"),
                c("🕗","восемь часов eight o clock","🕗"),
                c("🕘","девять часов nine o clock","🕘"),
                c("🕙","десять часов ten o clock","🕙"),
                c("🕚","одиннадцать часов eleven o clock","🕚"),
                c("🕛","двенадцать часов twelve o clock","🕛"),
                c("⌚","часы watch","⌚"),
                c("⏰","будильник alarm clock","⏰"),
                c("⏱️","секундомер stopwatch","⏱️"),
                c("⏲️","таймер timer","⏲️"),
                c("⌛","песочные часы hourglass done","⌛"),
                c("⏳","песочные часы hourglass not done","⏳"),
                c("📅","календарь calendar","📅"),
                c("📆","отрывной календарь tear-off calendar","📆"),
            ]
        },
    ]
})

# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  СБОРКА JSON                                                            ║
# ╚══════════════════════════════════════════════════════════════════════════╝

def build_json(minify=False):
    data = {
        "version": "2.0.0",
        "description": "jquery.charPicker data — emoji Unicode 15.1 + special characters",
        "groups": GROUPS
    }
    if minify:
        return json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    else:
        return json.dumps(data, ensure_ascii=False, indent=2)


def count_stats():
    total = 0
    for g in GROUPS:
        for sg in g.get('subgroups', []):
            total += len(sg.get('chars', []))
    print(f"Groups: {len(GROUPS)}")
    for g in GROUPS:
        cnt = sum(len(sg.get('chars', [])) for sg in g.get('subgroups', []))
        sgs = len(g.get('subgroups', []))
        print(f"  {g['id']:20s}  {sgs:2d} subgroups  {cnt:4d} chars")
    print(f"Total chars: {total}")


def main():
    parser = argparse.ArgumentParser(description='Generate charpicker-data.json')
    parser.add_argument('--output', '-o', default='charpicker-data.json',
                        help='Output file name (default: charpicker-data.json)')
    parser.add_argument('--minify', '-m', action='store_true',
                        help='Minify JSON output')
    parser.add_argument('--stats', '-s', action='store_true',
                        help='Print statistics and exit')
    args = parser.parse_args()

    if args.stats:
        count_stats()
        return

    output = build_json(minify=args.minify)

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(output)

    count_stats()
    print(f"\nSaved to: {args.output}  ({len(output):,} bytes)")


if __name__ == '__main__':
    main()
